/**
 * Slot RTP simulator (CLI).
 *
 * The PRD gate is that a game lands within 0.5% of its `rtpTarget` before it may be
 * set `is_active`. That verdict comes from the CLOSED-FORM figure in
 * `packages/shared/src/slots/exact.ts`, not from this simulation - a sampled RTP on a
 * high-volatility game swings close to a percentage point between seeds even at a
 * million rounds, which is wider than the tolerance being checked.
 *
 * What the simulation is for: corroborating the exact model against the real engine,
 * and measuring the things the closed form cannot give - hit frequency, volatility and
 * the win distribution.
 *
 *   npm run rtp -- --game reef-riches --spins 1000000
 *   npm run rtp -- --all --spins 1000000 --write-docs
 *
 * RNG modes:
 *   --rng crypto  (default) node:crypto randomInt, exactly as production
 *   --rng fast    a seeded xorshift, for quick iteration while tuning
 *
 * `fast` exists because tuning needs many large runs and crypto is far slower.
 * A sign-off run must be `crypto`; the generated report records which was used
 * and marks a `fast` run as invalid for sign-off.
 */
import { randomBytes } from "node:crypto";
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { exactRtp, getSlotConfig, listSlotSlugs, type SlotConfig } from "@luck-cays/shared";
import {
  BANDS,
  makeRng,
  simulate,
  withinTolerance,
  type RngMode,
  type SimResult,
} from "./simulate.js";

interface Args {
  games: string[];
  spins: number;
  bet: bigint;
  rng: RngMode;
  seed: number;
  writeDocs: boolean;
}

function parseArgs(argv: string[]): Args {
  const get = (flag: string): string | undefined => {
    const i = argv.indexOf(flag);
    return i >= 0 ? argv[i + 1] : undefined;
  };
  const has = (flag: string) => argv.includes(flag);

  const game = get("--game");
  const games = has("--all") || !game ? listSlotSlugs() : [game];

  const spins = Number(get("--spins") ?? 1_000_000);
  if (!Number.isInteger(spins) || spins < 1) {
    throw new Error("--spins must be a positive integer");
  }

  const rng = (get("--rng") ?? "crypto") as RngMode;
  if (rng !== "crypto" && rng !== "fast") {
    throw new Error("--rng must be crypto or fast");
  }

  return {
    games,
    spins,
    bet: BigInt(get("--bet") ?? "100"),
    rng,
    seed: Number(get("--seed") ?? 0) || randomBytes(4).readUInt32LE(0),
    writeDocs: has("--write-docs"),
  };
}

const pct = (n: number) => `${(n * 100).toFixed(3)}%`;
const pp = (n: number) => `${n >= 0 ? "+" : ""}${(n * 100).toFixed(3)}pp`;

function report(config: SlotConfig, r: SimResult, bet: bigint): string {
  const delta = r.rtp - config.rtpTarget;
  const exact = exactRtp(config);
  const lines = [
    `  RTP exact         ${pct(exact.rtp)}  (target ${pct(config.rtpTarget)}, delta ${pp(exact.rtp - config.rtpTarget)})  <- the authority`,
    `  within 0.5%       ${withinTolerance(exact.rtp, config.rtpTarget) ? "YES" : "NO"}  (on the exact figure)`,
    `  RTP sampled       ${pct(r.rtp)}  +/- ${(r.ci95 * 100).toFixed(3)}pp  (delta ${pp(delta)})`,
    `  sampling agrees   ${Math.abs(r.rtp - exact.rtp) <= r.ci95 ? "yes, within CI" : "NO - outside CI, investigate"}`,
    `  base game RTP     ${pct(Number(r.baseReturned) / Number(r.staked))}`,
    `  free spins RTP    ${pct(Number(r.freeReturned) / Number(r.staked))}`,
    `  hit frequency     ${pct(r.hits / r.rounds)}`,
    `  bonus trigger     ${pct(r.freeSpinTriggers / r.rounds)} (1 in ${(r.rounds / Math.max(r.freeSpinTriggers, 1)).toFixed(0)} rounds)`,
    `  free spins played ${r.freeSpinsPlayed.toLocaleString()}`,
    `  volatility (SD)   ${r.stdDev.toFixed(2)}x`,
    `  biggest round     ${(Number(r.maxRoundWin) / Number(bet)).toFixed(0)}x bet`,
    `  win distribution`,
  ];
  for (const [label] of BANDS) {
    const n = r.bands.get(label) ?? 0;
    if (n === 0) continue;
    lines.push(`    ${label.padEnd(12)} ${pct(n / r.rounds).padStart(8)}  (${n.toLocaleString()})`);
  }
  return lines.join("\n");
}

function docFor(config: SlotConfig, r: SimResult, args: Args): string {
  const exact = exactRtp(config);
  const delta = exact.rtp - config.rtpTarget;
  const ok = withinTolerance(exact.rtp, config.rtpTarget);
  const agrees = Math.abs(r.rtp - exact.rtp) <= r.ci95;
  const rngNote =
    args.rng === "crypto"
      ? "`crypto` (production path)"
      : "`fast` (seeded xorshift - tuning only, NOT valid for sign-off)";

  const distRows = BANDS.map(([label]) => {
    const n = r.bands.get(label) ?? 0;
    return n === 0 ? null : `| ${label} | ${pct(n / r.rounds)} | ${n.toLocaleString()} |`;
  })
    .filter((row): row is string => row !== null)
    .join("\n");

  return [
    `# RTP report - ${config.name} (\`${config.slug}\`)`,
    "",
    "Generated by `tools/rtp-sim`. Do not edit by hand; regenerate with:",
    "",
    "```bash",
    `npm run rtp -- --game ${config.slug} --spins ${args.spins} --write-docs`,
    "```",
    "",
    "## Verdict",
    "",
    `**Exact RTP ${pct(exact.rtp)}** against a target of ${pct(config.rtpTarget)} (${pp(delta)}).`,
    `Within the 0.5% tolerance: **${ok ? "YES" : "NO - must not go live"}**.`,
    "",
    "The exact figure is the authority, not the simulation. It is computed in closed form from",
    "the reel strips and paytable (see `packages/shared/src/slots/exact.ts`), so it has no",
    "sampling error at all. The simulation below exists to corroborate it: if the two disagree by",
    "more than the simulation's own confidence interval, the exact model and the live engine have",
    "drifted apart and that is a bug worth chasing.",
    "",
    "Monte Carlo alone could not sign this off. A high-volatility game's sampled RTP still swings",
    "close to a percentage point between seeds at a million rounds, which is wider than the",
    "tolerance being checked.",
    "",
    "## Exact figures",
    "",
    "| | |",
    "| --- | --- |",
    `| Target RTP | ${pct(config.rtpTarget)} |`,
    `| **Exact RTP** | **${pct(exact.rtp)}** |`,
    `| Delta from target | ${pp(delta)} |`,
    `| Base game lines | ${pct(exact.lineRtp)} |`,
    `| Scatter pays | ${pct(exact.scatterRtp)} |`,
    `| Free spin rounds | ${pct(exact.freeRtp)} |`,
    `| Free spins per base spin | ${exact.freeSpinsPerSpin.toFixed(4)} |`,
    `| Bonus trigger rate | ${pct(exact.triggerRate)} (1 in ${(1 / exact.triggerRate).toFixed(0)}) |`,
    "",
    "## Simulation (corroboration)",
    "",
    "| | |",
    "| --- | --- |",
    `| Run at | ${new Date().toISOString()} |`,
    `| Rounds simulated | ${r.rounds.toLocaleString()} |`,
    `| RNG | ${rngNote} |`,
    `| Sampled RTP | ${pct(r.rtp)} |`,
    `| 95% CI | +/- ${(r.ci95 * 100).toFixed(3)}pp |`,
    `| Agrees with the exact figure | ${agrees ? "yes, within CI" : "**NO - outside CI, investigate**"} |`,
    `| Hit frequency | ${pct(r.hits / r.rounds)} |`,
    `| Volatility (SD of round return) | ${r.stdDev.toFixed(2)}x |`,
    `| Biggest single round | ${(Number(r.maxRoundWin) / Number(args.bet)).toFixed(0)}x bet |`,
    "",
    "Hit frequency and volatility are measured, not computed. Hit frequency is the chance that at",
    "least one of 20 paylines pays, and paylines share cells, so there is no product formula for",
    "it - unlike expected value, which is immune to that dependence.",
    "",
    "## Win distribution",
    "",
    "| Round return | Share of rounds | Rounds |",
    "| --- | --- | --- |",
    distRows,
    "",
  ].join("\n");
}

function main(): void {
  const args = parseArgs(process.argv.slice(2));
  const seedNote = args.rng === "fast" ? ` seed=${args.seed}` : "";
  console.log(
    `RTP simulator: ${args.spins.toLocaleString()} rounds/game, bet ${args.bet}, rng=${args.rng}${seedNote}\n`,
  );

  let allPassed = true;

  for (const slug of args.games) {
    const config = getSlotConfig(slug);

    if (!config.betLevels.includes(Number(args.bet))) {
      console.warn(
        `  ! bet ${args.bet} is not a listed level for ${slug}; RTP is bet-independent so only the chip figures differ`,
      );
    }

    const r = simulate(config, {
      rounds: args.spins,
      bet: args.bet,
      rng: makeRng(args.rng, args.seed),
    });

    console.log(`${config.name} (${slug})`);
    console.log(report(config, r, args.bet));
    console.log(`  elapsed           ${(r.elapsedMs / 1000).toFixed(1)}s\n`);

    // The verdict is the exact figure's, not the sample's.
    if (!withinTolerance(exactRtp(config).rtp, config.rtpTarget)) allPassed = false;

    if (args.writeDocs) {
      const out = resolve(import.meta.dirname, "../../../docs/rtp", `${slug}.md`);
      mkdirSync(dirname(out), { recursive: true });
      writeFileSync(out, docFor(config, r, args));
      console.log(`  wrote docs/rtp/${slug}.md\n`);
    }
  }

  if (!allPassed) {
    console.error(
      "FAIL: at least one game is outside the 0.5% tolerance and must not be set active.",
    );
    process.exitCode = 1;
  }
}

main();
